project_id = "vvgtmfmvisxhivmldrhd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]

[functions.validate-license]
verify_jwt = false

[functions.heartbeat-license]
verify_jwt = false

[functions.create-license]
verify_jwt = true